Add missing setSessionId method to wizard store
Fix TypeError: setSessionId is not a function
The method was being called in handleUploadSuccess but didn't exist in the store.